#!/bin/bash
# Copyright (C) 2021,2022,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

LogTerm() {
  local term_log_type="${1^^}"
  local term_log_message="$2"

  local verbosity="${config[verbosity]^^}"

  case "$term_log_type" in
    TRACE)
      if [[ "$verbosity" != @(TRACE) ]]; then
        return 0
      fi
    ;;
    DEBUG)
      if [[ "$verbosity" != @(TRACE|DEBUG) ]]; then
        return 0
      fi
    ;;
    INFO)
      if [[ "$verbosity" != @(TRACE|DEBUG|INFO) ]]; then
        return 0
      fi
    ;;
    WARN)
      if [[ "$verbosity" != @(TRACE|DEBUG|INFO|WARN) ]]; then
        return 0
      fi
    ;;
    ERROR)
      if [[ "$verbosity" != @(TRACE|DEBUG|INFO|WARN|ERROR) ]]; then
        return 0
      fi
    ;;
    FATAL)
      if [[ "$verbosity" != @(TRACE|DEBUG|INFO|WARN|ERROR|FATAL) ]]; then
        return 0
      fi
    ;;
    CONFIG)
      if [[ "$verbosity" != @(TRACE|DEBUG|INFO) ]]; then
        return 0
      fi
    ;;
    *)
      if [[ "$verbosity" != @(TRACE|DEBUG) ]]; then
        return 0
      else
        Log debug "Invalid term log type '$term_log_type' in context '${FUNCNAME[2]}'"
      fi
    ;;
  esac

  printf '%s\n' "$term_log_type - $term_log_message" >&2
}
