#!/bin/bash
# Copyright (C) 2022-2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

CheckServerSupport() {
  Log debug "Got args '$*'"
  local -n __CheckServerSupport_version="$1" || {
    Log fatal "Empty or invalid reference."
    exit 1
  }

  Assert __CheckServerSupport_version || {
    Log info "No minimum server version defined for endpoint, skipping check."
    return 0
  }
  if [[ "$__CheckServerSupport_version" == "" ]]; then
    Log fatal "Empty version string passed."
    exit 1
  fi

  Log info "Checking if server supports the requested API..."
  local -a args=(
    keys=server_version
    format=plain
  )
  local server_version
  server_version="$(SynapseVersion args)" || return 1

  [[ "$__CheckServerSupport_version" =~ ([0-9]*)\.([0-9]*)\.([0-9]*)(rc[0-9][0-9]*)? ]] && {
    local minimum_major="${BASH_REMATCH[1]}"
    local minimum_minor="${BASH_REMATCH[2]}"
    local minimum_patch="${BASH_REMATCH[3]}"
    local minimum_release_candidate="${BASH_REMATCH[4]##rc}"
    minimum_release_candidate="${minimum_release_candidate:=99}"
  }

  [[ "$server_version" =~ ([0-9]*)\.([0-9]*)\.([0-9]*)(rc[0-9][0-9]*)? ]] && {
    local server_major="${BASH_REMATCH[1]}"
    local server_minor="${BASH_REMATCH[2]}"
    local server_patch="${BASH_REMATCH[3]}"
    local server_release_candidate="${BASH_REMATCH[4]##rc}"
    server_release_candidate="${server_release_candidate:=99}"
  }

   Log debug "Minimum version parts are '$minimum_major $minimum_minor $minimum_patch', release candidate '$minimum_release_candidate'"
   Log debug "Server version parts are '$server_major $server_minor $server_patch', release candidate '$server_release_candidate'"

  shopt -s extglob
  local adequate
  if (( "$server_major" > "$minimum_major" )); then
    Log debug "Major part is greater"
    adequate="true"
  elif (( "$server_major" == "$minimum_major" )) && (( "$server_minor" > "$minimum_minor" )); then
    Log debug "Major part is equal and minor part is equal or greater"
    adequate="true"
  elif [[ "${server_major}${server_minor}" == "${minimum_major}${minimum_minor}" ]] && (( "$server_patch" > "$minimum_patch" )); then
    Log debug "Major part and minor part are equal and patch part is greater"
    adequate="true"
  elif [[ "${server_version%%rc+(*)}" == "${__CheckServerSupport_version%%rc+(*)}" ]] && (( "$server_release_candidate" >= "$minimum_release_candidate" )); then
    Log debug "Major part, minor part, and patch part are equal and release candidate is equal or greater"
    adequate="true"
  else
    adequate="false"
  fi
  shopt -u extglob

  if [[ "$adequate" == true ]]; then
    Log info "Server meets minimum version requirement for the requested API, continuing..."
  else
    Log warn "Server failed to meet minimum version requirement for the requested API. Server version '${server_version}', minimum version '$__CheckServerSupport_version'"
    return 1
  fi
}
