#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseDeleteRoomStatus() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_delete_room_status_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray s_delete_room_status_url_params url_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Getting room deletion job status from '${config[homeserver]}'"

  local -n __SynapseDeleteRoomStatus_args="$1"
  local -A options
  ParseOptions __SynapseDeleteRoomStatus_args options || return 1

  # ask for job ID if not passed
  [[ -n "${options[id]}" ]] || {
    local input_job_id
    Read -r -p "Job ID:" input_job_id
    options[id]="$input_job_id"
  }
  url_params[job_id]="${options[id]}"
  Log debug "URL 'job_id' param set to '${url_params[job_id]}'"

  SetPathParameters url_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(status shutdown_room.kicked_users shutdown_room.failed_to_kick_users shutdown_room.local_aliases shutdown_room.new_room_id error)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values || return 1
  if [[ "${values[status]}" != "failed" ]]; then
    unset -v 'keys[-1]'
  fi

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
