#!/bin/bash
# Copyright (C) 2022-2023,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseDeleteUserRatelimit() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_delete_user_ratelimit_api api
  # copy path parameters to local map
  local -A path_params
  CopyArray s_delete_user_ratelimit_path_params path_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Deleting user ratelimit override on ${config[homeserver]}"

  local -n __SynapseDeleteUserRatelimit_args="$1"
  local -A options
  ParseOptions __SynapseDeleteUserRatelimit_args options || return 1
  # ask for username if not passed
  [[ -n "${options[user]}" ]] || {
    Read -r -p "Username: " input_user
      options[user]="$input_user"
      Log debug "Username is '${options[user]}'"
  }
  local mxid="@${options[user]}:${config[homeserver]}"
  PutArray path_params[user_id] "$mxid"
  Log debug "URL 'user_id' path param set to '${path_params[user_id]}'"

  SetPathParameters path_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [auth]='true'
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }
}
