#!/bin/bash
# Copyright (C) 2022-2023,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseEventReportsDelete() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_event_reports_delete_api api
  # copy path parameters to local map
  local -A path_params
  CopyArray s_event_reports_delete_path_params path_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Deleting event report from ${config[homeserver]}"

  local -n __SynapseEventReportsDelete_args="$1"
  local -A options
  ParseOptions __SynapseEventReportsDelete_args options || return 1
  # ask for report ID if not passed
  local report_id="${options[id]}"
  [[ -n "$report_id" ]] || {
    local input_report_id
    Read -r -p "Report ID to delete: " input_report_id
      report_id="$input_report_id"
  }
  ValidateInput integer "$report_id" || return 1
  PutArray path_params[report_id] "$report_id"
  Log debug "Report ID is '${path_params[report_id]}'"

  SetPathParameters path_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [auth]='true'
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }
}
