#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseUserRedactStatus() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_user_redact_status_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray s_user_redact_status_url_params url_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || return 1

  Log info "Getting user redaction job status from '${config[homeserver]}'"

  local -n __SynapseUserRedactStatus_args="$1"
  local -A options
  ParseOptions __SynapseUserRedactStatus_args options || return 1

  # ask for job ID if not passed
  local job_id="${options[id]}"
  [[ -n "$job_id" ]] || {
    local input_job_id
    Read -r -p "Job ID: " input_job_id
    job_id="$input_job_id"
  }
  url_params[job_id]="$job_id"
  Log debug "URL 'job_id' param set to '${url_params[job_id]}'"

  SetPathParameters url_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(status failed_redactions)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
