#!/bin/bash
# Copyright (C) 2021-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseUserUnshadowban() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_user_unshadowban_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray s_user_unshadowban_url_params url_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Un-shadowbanning user on homeserver ${config[homeserver]}"

  local -n __SynapseUserUnshadowban_args="$1"
  local -A options
  ParseOptions __SynapseUserUnshadowban_args options || return 1
  # input
  local username="${options[user]}"
  [[ -n "$username" ]] || {
    Read -r -p "Username to un-shadowban: " username
  }
  local user_id="@$username:${config[homeserver]}"
  Log debug "User ID is '$user_id'"
  PutArray url_params[user_id] "$user_id"
  Log debug "URL 'user_id' param set to '${url_params[user_id]}'"

  SetPathParameters url_params api[path]

  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [auth]='true'
  )
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }
}
