#!/bin/bash
# Copyright (C) 2022-2023,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseUserThreePIDLookup() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_user_threepid_lookup_api api
  # copy path parameters to local map
  local -A path_params
  CopyArray s_user_threepid_lookup_path_params path_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Looking up user by 3PID on ${config[homeserver]}"

  local -n __SynapseUserThreePIDLookup_args="$1"
  local -A options
  ParseOptions __SynapseUserThreePIDLookup_args options || return 1
  # input
  # ask for medium if not passed
  local medium="${options[medium]}"
  [[ -n "$medium" ]] || {
    Read -r -p "Medium: " medium
  }
  # ask for address if not passed
  local address="${options[address]}"
  [[ -n "$address" ]] || {
    Read -r -p "Address: " address
  }
  PutArray path_params[medium] "$medium"
  Log debug "URL 'medium' path param set to '${path_params[medium]}'"
  PutArray path_params[address] "$address"
  Log debug "URL 'address' path param set to '${path_params[address]}'"

  SetPathParameters path_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [auth]='true'
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(user_id)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
