#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseEventReports() {
  Log debug "Got args '$*'"

  local -n __SynapseEventReports_args="$1"
  case "${__SynapseEventReports_args[0]}" in
    details )
      ShiftArray __SynapseEventReports_args || return 1
      SynapseEventReportsDetails __SynapseEventReports_args || return 1
      return 0
    ;;
    delete )
      ShiftArray __SynapseEventReports_args || return 1
      SynapseEventReportsDelete __SynapseEventReports_args || return 1
      return 0
    ;;
  esac

  # copy api map to local map
  local -A api
  CopyArray s_event_reports_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray s_event_reports_url_params url_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || return 1

  Log info "Getting event reports from ${config[homeserver]}"

  local -A options
  ParseOptions __SynapseEventReports_args options

  # ask for limit if not passed
  local limit="${options[limit]}"
  [[ -n "$limit" ]] || {
    local input_limit
    Read -r -p "Maximum reports to return at once:" input_limit
      limit="$input_limit"
  }
  ValidateInput integer "$limit" || return 1
  url_params[limit]="$limit"
  Log debug "Limit is '${url_params[limit]}'"

  # use default `from` value if not passed
  local from="${options[from]}"
  [[ -n "$from" ]] && {
    ValidateInput integer "$from" || return 1
    url_params[from]="$from"
  }
  Log debug "From is '${url_params[from]}'"

  SetQueryString url_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get the values for the keys we are interested in
  local -a keys=(event_reports total next_token)
  local -A values
  ProcessResponse response[body] keys values || return 1

  local next_token="${values[next_token]}"
  local total="${values[total]}"
  ValidateInput integer "$next_token" || return 1
  ValidateInput integer "$total" || return 1

  # output
  output="${response[body]}"
  FormatOutput "${options[format]}" keys values output
  printf '%s\n' "$output"
  Log debug "Next token is '$next_token'"
  # paginate if necessary
  if (( $next_token > 0 )) && [[ "${FUNCNAME[*]}" =~ 'Prompt' ]]; then
    printf '%s\n' "Remaining: $(( $total - $next_token ))"
    local input_paginate
    Read -r -p "$(printf '%b' '\e[4mN\e[0mext/\e[4mR\e[0meturn: ')" input_paginate
      case "$input_paginate" in
        [Nn] ) SynapseEventReports "$limit" "$next_token";;
        [Rr] ) return 0;;
        *    ) return 0;;
      esac
  fi
}
