#!/bin/bash
# Copyright (C) 2021-2023,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseUserDeactivate() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_user_deactivate_api api
  # copy path parameters to local map
  local -A path_params
  CopyArray s_user_deactivate_path_params path_params
  # copy body parameters to local map
  local -A body_params
  CopyArray s_user_deactivate_body_params body_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Deactivating user on homeserver ${config[homeserver]}"

  local -n __SynapseUserDeactivate_args="$1"
  local -A options
  ParseOptions __SynapseUserDeactivate_args options || return 1
  # input
  local username="${options[user]}"
  [[ -n "$username" ]] || {
    Read -r -p "Username to deactivate: " username
  }
  if [[ "$username" == "${config[admin_user]}" ]]; then
    LogTerm warn "You are about to deactivate the account you are currently using! Deactivation is intended to be permanent and will likely have irreversible consequences."
    ConfirmContinue || return 1
  fi
  local user_id="@$username:${config[homeserver]}"
  Log debug "User ID is '$user_id'"
  PutArray path_params[user_id] "$user_id"
  Log debug "URL 'user_id' path param set to '${path_params[user_id]}'"
  local erase_profile="${options[erase]}"
  [[ -n "$erase_profile" ]] || {
    local input
    Read -r -p "Erase user profile? (Y/n): " input
    case "${input^^}" in
      Y|YES|'') erase_profile="true";;
      N|NO)     erase_profile="false";;
    esac
  }
  ValidateInput boolean "$erase_profile" || return 1
  PutArray body_params[erase] "$erase_profile"

  SetPathParameters path_params api[path]

  # construct request body
  local object
  ConstructObject s_user_deactivate body_params object || return 1

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [auth]='true'
    [data]="$object"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }
}
