#!/bin/bash
# Copyright (C) 2022-2023,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseUserRatelimit() {
  Log debug "Got args '$*'"
  local -n __SynapseUserRatelimit_args="$1"
  case "${__SynapseUserRatelimit_args[0]}" in
    'set')
      ShiftArray __SynapseUserRatelimit_args || return 1
      SynapseSetUserRatelimit __SynapseUserRatelimit_args || return 1
      return 0
    ;;
    'delete')
      ShiftArray __SynapseUserRatelimit_args
      SynapseDeleteUserRatelimit __SynapseUserRatelimit_args || return 1
      return 0
    ;;
  esac

  # copy api map to local map
  local -A api
  CopyArray s_user_ratelimit_api api
  # copy path parameters to local map
  local -A path_params
  CopyArray s_user_ratelimit_path_params path_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Getting ratelimit for user on ${config[homeserver]}"

  local -A options
  ParseOptions __SynapseUserRatelimit_args options || return 1
  # ask for user if not passed
  local user="${options[user]}"
  [[ -n "$user" ]] || {
    local input_user
    Read -r -p "Username: " input_user
      user="$input_user"
      Log debug "User is '$user'"
  }
  local mxid="@${user}:${config[homeserver]}"
  PutArray path_params[user_id] "$mxid"
  Log debug "URL 'user_id' path param set to '${path_params[user_id]}'"

  SetPathParameters path_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [auth]='true'
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(messages_per_second burst_count)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
