#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapsePurgeHistory() {
  Log debug "Got args '$*'"

  local -n __SynapsePurgeHistory_args="$1"
  if [[ "${__SynapsePurgeHistory_args[0]}" = "status" ]]; then
    ShiftArray __SynapsePurgeHistory_args || return 1
    SynapsePurgeHistoryStatus __SynapsePurgeHistory_args || return 1
    return 0
  fi

  # copy api map to local map
  local -A api
  CopyArray s_purge_history_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray s_purge_history_url_params url_params
  # copy body parameters to local map
  local -A body_params
  CopyArray s_purge_history_body_params body_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || return 1

  Log info "Purging history from ${config[homeserver]}"

  local -A options
  ParseOptions __SynapsePurgeHistory_args options || return 1
  # input
  local room_id="${options[id]}"
  [[ -n "$room_id" ]] || {
    Read -r -p "Room ID:" room_id
  }
  Log debug "Room ID is '$room_id'"
  url_params[room_id]="$room_id"
  Log debug "URL 'room_id' param set to '${url_params[room_id]}'"
  local timestamp="${options[timestamp]}"
  [[ -n "$timestamp" ]] || {
    Read -r -p "Relative date or timestamp:" timestamp
  }
  GetUnixTimestampMs "timestamp" || return 1
  Log debug "Unix timestamp is '$timestamp'"
  body_params[purge_up_to_ts]="$timestamp"
  local include_local_events="${options[include_local]}"
  [[ -n "$include_local_events" ]] || {
    local input
    Read -r -p "Delete local events? (y/N):" input
    case "$input" in
      [yY]|[Yy][Ee][Ss] ) include_local_events="true";;
      [Nn]|[Nn][Oo]     ) include_local_events="false";;
    esac
  }
  ValidateInput boolean "$include_local_events" || return 1
  body_params[delete_local_events]="$include_local_events"

  SetPathParameters url_params api[path]

  # construct request body
  local object
  ConstructObject s_purge_history body_params object || return 1

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [data]="$object"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(purge_id)
  local -A values
  ProcessResponse response[body] keys values || return 1

  # output
  echo -e "Purge Job ID: ${values[purge_id]}\n"
}
