#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseForwardExtremities() {
  Log debug "Got args '$*'"

  local -n __SynapseForwardExtremities_args="$1"
  if [[ "${__SynapseForwardExtremities_args[0]}" == "delete" ]]; then
    ShiftArray __SynapseForwardExtremities_args || return 1
    SynapseDeleteForwardExtremities __SynapseForwardExtremities_args || return 1
    return 0
  fi

  # copy api map to local map
  local -A api
  CopyArray s_forward_extremities_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray s_forward_extremities_url_params url_params


  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || return 1

  Log info "Checking forward extremities on ${config[homeserver]}"

  local -A options
  ParseOptions __SynapseForwardExtremities_args options
  # ask for room ID or alias if not passed
  [[ -n "${options[room]}" ]] || {
    Read -r -p "Room ID or alias:" input_room
      options[room]="$input_room"
      Log debug "Room is '${options[room]}'"
  }
  url_params[room_id_or_alias]="${options[room]}"
  Log debug "URL 'room_id_or_alias' param set to '${url_params[room_id_or_alias]}'"

  SetPathParameters url_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(results count)
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  echo "$output"
}
