#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseDeleteRoom() {
  Log debug "Got args '$*'"
  local -n __SynapseDeleteRoom_args="$1"
  if [[ "${__SynapseDeleteRoom_args[0]}" = "status" ]]; then
    ShiftArray __SynapseDeleteRoom_args
    SynapseDeleteRoomStatus __SynapseDeleteRoom_args || return 1
    return 0
  fi

  # copy api map to local map
  local -A api
  CopyArray s_delete_room_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray s_delete_room_url_params url_params
  # copy body parameters to local map
  local -A body_params
  CopyArray s_delete_room_body_params body_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Deleting room from ${config[homeserver]}"

  local -A options
  ParseOptions __SynapseDeleteRoom_args options || return 1
  # input
  local room="${options[room]}"
  [[ -n "$room" ]] || {
    Read -r -p "Room: " room
  }
  [[ "${room:0:1}" == '#' ]] && {
    local -a args=(
      alias="$room"
      keys=room_id
      format=plain
    )
    room="$(MatrixResolveAlias args)" || return 1
  }
  url_params[room_id]="$room"
  Log debug "URL 'room_id' param set to '${url_params[room_id]}'"

  local block="${options[block]}"
  [[ -n "$block" ]] || {
    local input_block_joins
    Read -r -p "Block users from rejoining the room? (y/N): " input_block_joins
    case "${input_block_joins^^}" in
      Y|YES)   block='true';;
      N|NO|'') block='false';;
    esac
  }
  ValidateInput boolean "$block" || return 1
  body_params[block]="$block"

  local purge="${options[purge]}"
  [[ -n "$purge" ]] || {
    local input_purge
    Read -r -p "Purge all events? (y/N): " input_purge
    case "${input_purge^^}" in
      Y|YES)   purge='true';;
      N|NO|'') purge='false';;
    esac
  }
  ValidateInput boolean "$purge" || return 1
  body_params[purge]="$purge"

  local migrate="${options[migrate]}"
  [[ -n "$migrate" ]] || {
    local input_migrate
    Read -r -p "Migrate users to new room? (y/N): " input_migrate
    case "${input_migrate^^}" in
      Y|YES)   migrate='true';;
      N|NO|'') migrate='false';;
    esac
  }
  ValidateInput boolean "$migrate" || return 1
  if [[ "$migrate" == true ]]; then
    local mxid="${options[mxid]}"
    [[ -n "$mxid" ]] || {
      Read -r -p "New room user MXID: " mxid
    }
    body_params[new_room_user_id]="$mxid"

    local room_name="${options[room_name]}"
    [[ -n "$room_name" ]] || {
      Read -r -p "New room name: " room_name
    }
    ValidateInput text "$room_name" || return 1
    body_params[room_name]="$room_name"

    local message="${options[message]}"
    [[ -n "$message" ]] || {
      Read -r -p "New room message: " message
    }
    ValidateInput text "$message" || return 1
    body_params[message]="$message"
  fi

  SetPathParameters url_params api[path]

  # construct request body
  local object
  ConstructObject s_delete_room body_params object || return 1

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [data]="$object"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(delete_id)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
