#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseDeleteForwardExtremities() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_delete_forward_extremities_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray s_delete_forward_extremities_url_params url_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Deleting forward extremities on ${config[homeserver]}"

  local -n __SynapseDeleteForwardExtremities_args="$1"
  local -A options
  ParseOptions __SynapseDeleteForwardExtremities_args options
  # ask for room ID or alias if not passed
  [[ -n "${options[room]}" ]] || {
    local input_room
    Read -r -p "Room ID or alias: " input_room
      options[room]="$input_room"
      Log debug "Room is '${options[room]}'"
  }
  url_params[room_id_or_alias]="${options[room]}"
  Log debug "URL 'room_id_or_alias' param set to '${url_params[room_id_or_alias]}'"

  SetPathParameters url_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(deleted)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
