#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseRoomDetails() {
  Log debug "Got args '$*'"
  # copy api map to local map
  local -A api
  CopyArray s_room_details_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray s_room_details_url_params url_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Getting room details from ${config[homeserver]}"

  local -n __SynapseRoomDetails_args="$1"
  local -A options
  ParseOptions __SynapseRoomDetails_args options || return 1
  # input
  local room="${options[room]:-${options[id]}}"
  [[ -n "$room" ]] || {
    Read -r -p "Room: " room
  }
  [[ "${room:0:1}" == '#' ]] && {
    local -a args=(
      alias="$room"
      keys=room_id
      format=plain
    )
    room="$(MatrixResolveAlias args)" || return 1
  }
  Log debug "Room ID is '$room'"
  ValidateInput text "$room" || return 1
  PutArray url_params[room_id] "$room"
  Log debug "URL 'room_id' param set to '${url_params[room_id]}'"

  SetPathParameters url_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(room_id room_type name avatar topic canonical_alias joined_members joined_local_members joined_local_devices version creator encryption federatable public join_rules guest_access history_visibility state_events forgotten)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
