#!/bin/bash
# Copyright (C) 2021-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseVersion() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_version_api api

  CheckLoginStatus || return 1

  # only proceed if we have a configured homeserver
  [[ -n "${config[homeserver]}" ]] || {
    Log error "Failed to get server version. No homeserver is configured."
    return 1
  }

  # parse options
  local -n __SynapseVersion_args="$1"
  local -A options
  ParseOptions __SynapseVersion_args options || return 1

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(server_version python_version)
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
