#!/bin/bash
# Copyright (C) 2022-2023,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

SynapseDestinationReset() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray s_destination_reset_api api
  # copy path parameters to local map
  local -A path_params
  CopyArray s_destination_reset_path_params path_params

  CheckLoginStatus || return 1
  CheckServerSupport 'api[minimum_version]' || {
    ConfirmContinue || return 1
  }

  Log info "Getting destination reset from ${config[homeserver]}"

  local -n __SynapseDestinationReset_args="$1"
  local -A options
  ParseOptions __SynapseDestinationReset_args options || return 1
  # input
  [[ -n "${options[destination]}" ]] || {
    local input_destination
    Read -r -p "Destination: " input_destination
      options[destination]="$input_destination"
  }
  Log debug "Destination is '${options[destination]}'"
  ValidateInput host "${options[destination]}" || return 1
  PutArray path_params[destination] "${options[destination]}"
  Log debug "URL 'destination' path param set to '${path_params[destination]}'"

  SetPathParameters path_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [auth]='true'
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # TODO: output
}
