kind: pipeline
name: release

trigger:
  event:
    - tag

steps:
  - name: "Build Script"
    image: ubuntu
    pull: if-not-exists
    commands:
      - chmod +x ./utils/linac
      - mkdir build
      - ./utils/linac build axon.sh.build
      - mv build/axon.sh axon.sh

  - name: "Sign Release Artifacts"
    image: plugins/gpgsign
    settings:
      key:
        from_secret: gpg_key
      passphrase:
        from_secret: key_passphrase
      files:
        - axon.sh
      detach_sign: true

  - name: "Create Gitea Release"
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: api_key
      base_url: https://git.thisisjoes.site
      files:
        - axon.sh
        - axon.sh.asc
      checksum:
        - md5
        - sha256
      title: "${DRONE_TAG}"
      prerelease: false

---
kind: pipeline
name: tests

trigger:
  branch:
    - dev

steps:
  - name: "setup synapse"
    image: matrixdotorg/synapse:latest
    volumes:
      - name: data
        path: /data
    environment:
      SECRET:
        from_secret: shared_secret
    commands:
      - generate_config --generate-secrets --report-stats no --server-name synapse.thisisjoes.test --data-dir /data --config-dir /data --output-file /data/homeserver.yaml
      - 'sed -i "s/registration_shared_secret:.*/registration_shared_secret: \"$SECRET\"/g" /data/homeserver.yaml'
      - 'sed -i "s/''    - 127.0.0.1''//g" /data/homeserver.yaml'
      - 'sed -i "s/''::1''/''0.0.0.0''/g" /data/homeserver.yaml'
      - 'sed -i "s/8008/443/g" /data/homeserver.yaml'
      - 'echo "serve_server_wellknown: true" >> /data/homeserver.yaml'

  - name: "synapse.thisisjoes.test"
    image: matrixdotorg/synapse:latest
    volumes:
      - name: data
        path: /data
    environment:
      UID: 0
    detach: true

  - name: "create admin user"
    image: matrixdotorg/synapse:latest
    volumes:
      - name: data
        path: /data
    environment:
      PASSWORD:
        from_secret: admin_password
      SECRET:
        from_secret: shared_secret
    commands:
      - while ! curl --silent --max-time 5  'http://synapse.thisisjoes.test:443/_matrix/static'; do sleep 1; done
      - register_new_matrix_user --admin --user admin --password "$PASSWORD" --shared-secret "$SECRET" 'http://synapse.thisisjoes.test:443'

  - name: "run function tests"
    image: bats/bats
    pull: if-not-exists
    commands:
      - apk --no-cache --update add jq curl
      - bats ./tests/functions

  - name: "build axon"
    image: git.thisisjoes.site/joe/linac:latest
    commands:
      - linac build axon.sh.build

  - name: "login"
    image: registry.gitlab.com/gitlab-ci-utils/curl-jq@sha256:9f4348791233494a24ad24b3a426652b93b5483696a4af65a419b97f7a8c19be
    pull: if-not-exists
    environment:
      PASSWORD:
        from_secret: admin_password
      AXON_CONFIG: 'verbosity=info:scheme=http:config_path=axon:log_level=none'
    commands:
      - echo "$PASSWORD" >> passwd
      - chmod +x build/axon.sh
      - 'build/axon.sh login mxid="@admin:synapse.thisisjoes.test" password_file=passwd save_token=true'

  - name: "run command tests"
    image: bats/bats
    pull: if-not-exists
    environment:
      AXON_CONFIG: 'verbosity=info:scheme=http:config_path=axon:log_level=none'
    commands:
      - apk --no-cache --update add jq curl
      - bats ./tests/commands

volumes:
  - name: data
    temp: {}
