#!/bin/bash
# Copyright (C) 2021-2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

Assert() {
  Log debug "Got args '$*'"
  case $# in
    0 ) Log fatal "No parameters passed."; exit 1;;
    1 ) local -n variable="$1"
        local variable_name="${!variable}"
        Log debug "Variable name is '$variable_name'"
        local value="$variable"
        Log debug "Value is '$value'"
        local varbase="${variable_name%%\[*]}"
        Log debug "varbase is '$varbase'"
        local type declared='false'
        GetType "$varbase" type
        if [[ "$type" =~ (ARRAY|HASH) && "$varbase" != "$variable_name" ]]; then
          Log debug "Type is '$type'."
          if [[ -v "$variable_name" ]]; then
            declared='true'
          fi
        else
          if declare -p "$variable_name" &>/dev/null; then
            declared='true'
          fi
        fi

        if [[ "$declared" == 'true' ]]; then
          Log debug "Variable '$variable_name' is declared."
          return 0
        else
          Log debug "Variable '$variable_name' is not declared."
          return 1
        fi
      ;;
    2 ) local variable_name="$1"
        Log debug "Variable_name is '$variable_name'"
        local value="${!variable_name}"
        Log debug "Value is '$value'"
        local varbase="${variable_name%%\[*]}"
        local type
        GetType "$varbase" type
        Log debug "Type is '$type'"
        local desired_type="$2"
        Log debug "Desired type is '$desired_type'"
        if [[ "$type" == "$desired_type" ]]; then
          Log debug "Types match."
          return 0
        else
          Log fatal "Assertion failed, variable '$variable_name' is of type '$type', expected '$desired_type'."
          exit 1
        fi
      ;;
    * ) Log fatal "Received too many parameters."; exit 1;;
  esac
}
