#!/bin/bash
# Copyright (C) 2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

CheckType() {
  Log debug "Got args '$*'"

  local variable_to_check
  variable_to_check="$(declare -p "$1" 2>/dev/null)"
  [[ -n "$variable_to_check" ]] || {
    Log error "Cannot check type of undefined variable."
    return 1
  }
  local -n __CheckType_type="$2" || return 1

  local pattern
  pattern='^declare -n[^=]+=\"([^\"]+)\"$'
  while [[ $variable_to_check =~ $pattern ]]; do
    Log debug "Passed variable is a name reference, resolving to referenced variable."
    variable_to_check="$(declare -p "${BASH_REMATCH[1]}")"
  done
  Log debug "Checking type of variable declared by '${variable_to_check%%=*}'."

  case "${variable_to_check#declare -}" in
    a* ) __CheckType_type='ARRAY';;
    A* ) __CheckType_type='HASH';;
    i* ) __CheckType_type='INT';;
    x* ) __CheckType_type='EXPORT';;
    *  ) __CheckType_type='OTHER';;
  esac

  Log debug "Variable type is '$__CheckType_type'."
}
