#!/bin/bash
# Copyright (C) 2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

ConfirmContinue() {
  case "${config[verbosity]^^}" in
    (ERROR|NONE)
      Log warn "Skipping user confirmation due to reduced verbosity configuration."
      return 0
    ;;
  esac

  local response
  Read -r -p "$(printf '%s' 'Continue anyway? (y/N)')" response
  case "$response" in
    [Yy]|[Yy][Ee][Ss] ) Log info "Got affirmative response, continuing..."; return 0;;
    [Nn]|[Nn][Oo]|''  ) Log info "Got negative or empty response, aborting"; return 1;;
    *                 ) Log error "Invalid response '$response'"; ConfirmContinue;;
  esac
}
