#!/bin/bash
# Copyright (C) 2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

ConvertIntervalMs() {
  Log debug "Got args '$*'"
  local interval="$1"
  [[ -n "$interval" ]] || {
    Log error "Cannot convert empty interval."
    return 1
  }

  local unit
  if (( "$interval" >= 86400000 )); then
    interval=$(( "${interval::-3}"  / 86400))
    unit="days"
  elif (( "$interval" >= 3600000 )); then
    interval=$(( "${interval::-3}" / 3600  ))
    unit="hours"
  elif (( "$interval" >= 60000 )); then
    interval=$(( "${interval::-3}" / 60 ))
    unit="minutes"
  elif (( "$interval" >= 1000 )); then
    interval="${interval::-3}"
    unit="seconds"
  else
    unit="milliseconds"
  fi

  printf '%s %s' "$interval" "$unit"
}
