#!/bin/bash
# Copyright (C) 2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

DestroySession() {
  MatrixLogout || {
    Log warn "Failed to properly logout from homeserver."
  }

  # remove user and session configuration
  Log info "Destroying local session..."
  config[admin_user]=""
  config[admin_token]=""
  config[device_id]=""
  WriteConfiguration || {
    Log fatal "Failed to write updated config to file. Session information may remain in '${config[config_path]}/${config[config_file]}'."
    exit 1
  }
}
