#!/bin/bash
# Copyright (C) 2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

GetType() {
  Log debug "Got args '$*'"

  local var
  var="$(declare -p "$1" 2>/dev/null)"
  [[ -n "$var" ]] || {
    Log error "Cannot get type of undefined variable."
    return 1
  }
  local -n __GetType_type="$2" || return 1

  local pattern
  pattern='^declare -n[^=]+=\"([^\"]+)\"$'
  while [[ $var =~ $pattern ]]; do
    Log debug "Passed variable is a name reference, resolving to referenced variable."
    var="$(declare -p "${BASH_REMATCH[1]}")"
  done
  Log debug "Getting type of variable declared by '${var%%=*}'."

  case "${var#declare -}" in
    a* ) __GetType_type='ARRAY';;
    A* ) __GetType_type='HASH';;
    i* ) __GetType_type='INT';;
    x* ) __GetType_type='EXPORT';;
    *  ) __GetType_type='OTHER';;
  esac

  Log debug "Variable type is '$__GetType_type'."
}
