#!/bin/bash
# Copyright (C) 2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only
PutArray() {
  Log debug "Got args '$*'"
  local -n __PutArray_element="$1" || {
    Log fatal "Empty or invalid reference."
    exit 1
  }
  local value="$2"

  Assert __PutArray_element || {
    Log fatal "Cannot set value of undeclared element '$1'."
    exit 1
  }

  __PutArray_element="$value"
}
