#!/bin/bash
# Copyright (C) 2021,2022,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

DestinationCommandHandler() {
  Log debug "Got args '$*'"
  local -n __DestinationCommandHandler_args="$1"
  local subcommand="${__DestinationCommandHandler_args[0]}"
  ShiftArray __DestinationCommandHandler_args
  Log debug "Testing '$subcommand'"
  case "$subcommand" in
    discover ) MatrixDiscover __DestinationCommandHandler_args;;
    list     ) SynapseDestinationList __DestinationCommandHandler_args;;
    details  ) SynapseDestinationDetails __DestinationCommandHandler_args;;
    reset    ) SynapseDestinationReset __DestinationCommandHandler_args;;
    rooms    ) SynapseDestinationRooms __DestinationCommandHandler_args;;
    version  ) MatrixServerVersion __DestinationCommandHandler_args;;
    ''       ) Log error "Subcommand required. Type 'help destination' for a list of subcommands."; return 1;;
    *        ) Log error "Unrecognized subcommand '$subcommand'. Type 'help destination' for a list of subcommands."; return 1;;
  esac
}
