#!/bin/bash
# Copyright (C) 2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

HandleCommand() {
  Log debug "Got args '$*'"
  local -n __HandleCommand_args="$1"
  Assert __HandleCommand_args ARRAY
  local command="${__HandleCommand_args[0]}"
  ShiftArray __HandleCommand_args

  case "$command" in
    login       ) MatrixLogin __HandleCommand_args;;
    logout      )
      LogTerm warn "Your local session will be erased and your access token will be invalidated."
      ConfirmContinue || return 1
      DestroySession
    ;;
    whoami      ) MatrixWhoAmI __HandleCommand_args;;
    server      ) ServerCommandHandler __HandleCommand_args;;
    destination ) DestinationCommandHandler __HandleCommand_args;;
    room        ) RoomCommandHandler __HandleCommand_args;;
    user        ) UserCommandHandler __HandleCommand_args;;
    config      ) Configure __HandleCommand_args;;
    version     ) printf '%s\n' "$projectName v$projectVersion";;
    help        ) PrintHelp __HandleCommand_args;;
    warranty    ) PrintInfo warranty;;
    conditions  ) PrintInfo conditions;;
    exit        ) Exit;;
    *           ) printf '%s\n' "Unrecognized command '$command'. Type 'help' for help.";;
  esac
}
