#!/bin/bash
# Copyright (C) 2021-2022,2024-2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

RoomCommandHandler() {
  Log debug "Got args '$*'"
  local -n __RoomCommandHandler_args="$1"
  local subcommand="${__RoomCommandHandler_args[0]}"
  ShiftArray __RoomCommandHandler_args
  Log debug "Testing '$subcommand'"

  case "$subcommand" in
    purge       ) SynapsePurgeHistory __RoomCommandHandler_args;;
    delete      ) SynapseDeleteRoom __RoomCommandHandler_args;;
    evacuate    ) SynapseDeleteRoom __RoomCommandHandler_args;;
    extremities ) SynapseForwardExtremities __RoomCommandHandler_args;;
    details     ) SynapseRoomDetails __RoomCommandHandler_args;;
    alias       ) MatrixResolveAlias __RoomCommandHandler_args;;
    visibility  ) MatrixGetRoomVisibility __RoomCommandHandler_args;;
    ''          ) Log error "Subcommand required. Type 'help room' for a list of subcommands.";;
    *           ) Log error "Unrecognized subcommand '$subcommand'. Type 'help room' for a list of subcommands.";;
  esac
}
