#!/bin/bash
# Copyright (C) 2021,2022,2025.2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

UserCommandHandler() {
  Log debug "Got args '$*'"
  local -n __UserCommandHandler_args="$1"
  local subcommand="${__UserCommandHandler_args[0]}"
  ShiftArray __UserCommandHandler_args
  Log debug "Testing '$subcommand'"

  case "$subcommand" in
    rooms      ) SynapseUserJoinedRooms __UserCommandHandler_args;;
    threepid   ) SynapseUserThreePIDLookup __UserCommandHandler_args;;
    create     ) SynapseUserCreate __UserCommandHandler_args;;
    password   ) SynapseUserResetPassword __UserCommandHandler_args;;
    ratelimit  ) SynapseUserRatelimit __UserCommandHandler_args;;
    redact     ) SynapseUserRedact __UserCommandHandler_args;;
    deactivate ) SynapseUserDeactivate __UserCommandHandler_args;;
    shadowban  ) SynapseUserShadowban __UserCommandHandler_args;;
    unshadowban) SynapseUserUnshadowban __UserCommandHandler_args;;
    join       ) SynapseUserJoinRoom __UserCommandHandler_args;;
    ''         ) Log error "Subcommand required. Type 'help user' for a list of subcommands."; return 1;;
    *          ) Log error "Unrecognized subcommand '$subcommand'. Type 'help user' for a list of subcommands."; return 1;;
  esac
}
