#!/bin/bash
# Copyright (C) 2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

EncodeJSON() {
  Log debug "Got args '$*'."
  local string="$1"
  local -n __EncodeJSON_json="$2"
  local std_out
  local std_err
  CatchStream std_out std_err jq --raw-input --slurp <<<"$string" || {
    Log fatal "Failed to encode string as JSON, jq returned error '$std_err'."
    exit 1
  }
  __EncodeJSON_json="${std_out//\\n\"/\"}"
}
