#!/bin/bash
# Copyright (C) 2021-2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

ProcessResponse() {
  Log debug "Got args $*"
  local -n __ProcessResponse_body="$1"
  local -n __ProcessResponse_keys="$2"
  local -n __ProcessResponse_values="$3"

  ValidateJSON "$__ProcessResponse_body" || return 1

  for key in "${__ProcessResponse_keys[@]}"; do
    Log debug "Trying key '$key'"
    local parts
    local IFS='.'
    read -r -a parts <<<"${key#.}"
    unset IFS
    if (( "${#parts[@]}" > 1 )); then
      Log debug "Got multipart key selector."
      local arg=''
      for part in "${parts[@]}"; do
        Log debug "Part is '$part'."
        if [[ "$part" == 'm'  ]]; then
          Log debug "Part is 'm' prefix."
          arg+="\"$key\""
          Log debug "Arg is '$arg'."
          break
        else
          if [[ "$part" =~ \[[0123456789]*\]$ ]]; then
            Log debug "Part is array selector."
            arg+="\"${part%%\[[0123456789]\]}\"${part//*\[/\[}."
          else
            arg+="\"$part\"."
          fi
        fi
      done
      arg="${arg%.}"
      Log debug "Trimmed arg is '$arg'."
    else
      local arg
      if [[ "$key" =~ \[[0123456789]*\]$ ]]; then
        Log debug "Key is array selector."
        arg="\"${key%%\[[0123456789]\]}\"${key//*\[/\[}"
      else
        arg="\"$key\""
      fi
    fi

    Log debug "Final arg is '.$arg'."
    local value; value="$(jq --raw-output --compact-output --exit-status -- ".$arg" <<< "$__ProcessResponse_body")"
    __ProcessResponse_values+=(["$key"]="$value")
    Log debug "Got value '${__ProcessResponse_values[$key]}'"
  done
}
