#!/bin/bash
# Copyright (C) 2021-2023,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

DefineSynapseQueryParameters() {
  declare -Agr s_destination_list_query_params=(
    [from]="0"
    [limit]="30"
    [dir]="f"
    [order_by]="destination"
  )

  declare -Agr s_destination_rooms_query_params=(
    [from]="0"
    [limit]="30"
    [dir]="f"
  )

  declare -Agr s_event_reports_query_params=(
    [from]="0"
    [limit]="3"
    [dir]="b"
    [user_id]=""
    [room_id]=""
  )
}
