#!/bin/bash
DefineOutputStrings() {
  local locale="${config[locale]:-en}"
  case "$locale" in
    en )
      declare -Agr output_strings=(
        [avatar]='Avatar'
        [base_url]='Base URL'
        [burst_count]='Burst count'
        [canonical_alias]='Canonical alias'
        [count]='Count'
        [creator]='Creator'
        [deleted]='Deleted'
        [delete_id]='Deletion job ID'
        [destination]='Destination'
        [encryption]='Encryption'
        [error]='Error'
        [event_id]='Event ID'
        [event_json]='Event JSON'
        [failed]='Failed'
        [failed_redactions]='Failed redactions'
        [failure_ts]='Failed at'
        [federatable]='Federatable'
        [filtered]='Filtered'
        [forgotten]='Forgotten'
        [guest_access]='Guest access'
        [history_visibility]='History visibility'
        [join_rules]='Join rules'
        [joined_local_devices]='Joined local devices'
        [joined_local_members]='Joined local members'
        [joined_members]='Joined members'
        [joined_rooms]='Joined rooms'
        [last_successful_stream_ordering]='Last successful stream ordering'
        [members]='Members'
        [messages_per_second]='Messages per second'
        [name]='Name'
        [public]='Public'
        [python_version]='Python version'
        [redact_id]='Redaction job ID'
        [retry_interval]='Retry interval'
        [retry_last_ts]='Last retried at'
        [room_id]='Room ID'
        [room_type]='Room type'
        [servers]='Servers'
        [server_version]="Server version"
        [shutdown_room.failed_to_kick_users]='Failed to kick users'
        [shutdown_room.kicked_users]='Kicked users'
        [shutdown_room.local_aliases]='Local aliases found'
        [shutdown_room.new_room_id]='New room ID'
        [state_events]='State events'
        [status]='Status'
        [topic]='Topic'
        [total]='Total'
        [user_id]='User ID'
        [version]='Version'
      )
    ;;
  esac
}
