#!/bin/bash
# Copyright (C) 2021-2024,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

DefineMatrixBodyParameters() {
  declare -Agr m_login_body_params=(
    [type]="m.login.password"
    [identifier]="m.id.user"
    [user]=""
    [password]=""
    [token]=""
    [device_id]=""
  )

  declare -Agr m_create_alias_body_params=(
    [room_id]=""
  )

  declare -Agr m_room_visibility_body_params=(
    [visibility]="public"
  )

  declare -Agr m_room_create_body_params=(
    [creation_content.m.federate]="false"
    [preset]="private_chat"
    [name]=""
    [topic]=""
  )
}
