#!/bin/bash
# Copyright (C) 2021-2023,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

DefineSynapseEndpoints() {
  declare -Agr s_version_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/server_version"
    [path_params]=""
    [body_params]=""
  )

  declare -Agr s_destination_list_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/federation/destinations"
    [query_params]="s_destination_list_query_params"
    [body_params]=""
    [minimum_version]="1.49.0rc1"
  )

  declare -Agr s_destination_details_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/federation/destinations/DESTINATION"
    [path_params]="s_destination_details_path_params"
    [body_params]=""
  )

  declare -Agr s_destination_reset_api=(
    [method]="POST"
    [path]="/_synapse/admin/v1/federation/destinations/DESTINATION/reset_connection"
    [path_params]="s_destination_reset_path_params"
    [body_params]=""
    [minimum_version]="1.52.0rc1"
  )

  declare -Agr s_destination_rooms_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/federation/destinations/DESTINATION/rooms"
    [path_params]="s_destination_rooms_path_params"
    [query_params]="s_destination_rooms_query_params"
    [body_params]=""
    [minimum_version]="1.52.0rc1"
  )

  declare -Agr s_server_notice_api=(
    [method]="POST"
    [path]="/_synapse/admin/v1/send_server_notice"
    [path_params]=""
    [body_params]="s_server_notice_body_params"
  )

  declare -Agr s_event_reports_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/event_reports"
    [query_params]="s_event_reports_query_params"
    [body_params]=""
    [minimum_version]="1.21.0rc1"
  )

  declare -Agr s_event_reports_details_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/event_reports/REPORT_ID"
    [path_params]="s_event_reports_details_path_params"
    [body_params]=""
    [minimum_version]="1.23.0rc1"
  )

  declare -Agr s_event_reports_delete_api=(
    [method]="DELETE"
    [path]="/_synapse/admin/v1/event_reports/REPORT_ID"
    [path_params]="s_event_reports_delete_path_params"
    [body_params]=""
    [minimum_version]="1.79.0rc1"
  )

  declare -Agr s_room_details_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/rooms/ROOM_ID"
    [path_params]="s_room_details_path_params"
    [body_params]=""
    [minimum_version]="1.14.0rc1"
  )

  declare -Agr s_room_members_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/rooms/ROOM_ID/members"
    [path_params]="s_room_members_path_params"
    [body_params]=""
  )

  declare -Agr s_purge_history_api=(
    [method]="POST"
    [path]="/_synapse/admin/v1/purge_history/ROOM_ID"
    [path_params]="s_purge_history_path_params"
    [body_params]="s_purge_history_body_params"
  )

  declare -Agr s_purge_history_status_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/purge_history_status/JOB_ID"
    [path_params]="s_purge_history_status_path_params"
    [body_params]=""
  )

  declare -Agr s_delete_room_api=(
    [method]="DELETE"
    [path]="/_synapse/admin/v2/rooms/ROOM_ID"
    [path_params]="s_delete_room_path_params"
    [body_params]="s_delete_room_body_params"
    [minimum_version]="1.48.0rc1"
  )

  declare -Agr s_delete_room_status_api=(
    [method]="GET"
    [path]="/_synapse/admin/v2/rooms/delete_status/JOB_ID"
    [path_params]="s_delete_room_status_path_params"
    [body_params]=""
    [minimum_version]="1.48.0rc1"
  )

  declare -Agr s_forward_extremities_api=(
    [method]="GET"
    [path]='/_synapse/admin/v1/rooms/ROOM_ID_OR_ALIAS/forward_extremities'
    [path_params]="s_forward_extremities_path_params"
    [body_params]=""
    [minimum_version]="1.27.0rc1"
  )

  declare -Agr s_delete_forward_extremities_api=(
    [method]="DELETE"
    [path]='/_synapse/admin/v1/rooms/ROOM_ID_OR_ALIAS/forward_extremities'
    [path_params]="s_delete_forward_extremities_path_params"
    [body_params]=""
    [minimum_version]="1.27.0rc1"
  )

  declare -Agr s_user_query_api=(
    [method]="GET"
    [path]="/_synapse/admin/v2/users/USER_ID"
    [path_params]="s_user_query_path_params"
    [body_params]=""
  )

  declare -Agr s_user_joined_rooms_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/users/USER_ID/joined_rooms"
    [path_params]="s_user_joined_rooms_path_params"
    [body_params]=""
  )

  declare -Agr s_user_threepid_lookup_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/threepid/MEDIUM/users/ADDRESS"
    [path_params]="s_user_threepid_lookup_path_params"
    [body_params]=""
    [minimum_version]="1.72.0rc1"
  )

  declare -Agr s_user_create_api=(
    [method]="PUT"
    [path]="/_synapse/admin/v2/users/USER_ID"
    [path_params]="s_user_create_path_params"
    [body_params]="s_user_create_body_params"
  )

  declare -Agr s_user_reset_password_api=(
    [method]="POST"
    [path]="/_synapse/admin/v1/reset_password/USER_ID"
    [path_params]="s_user_reset_password_path_params"
    [body_params]="s_user_reset_password_body_params"
  )

  declare -Agr s_user_ratelimit_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/users/USER_ID/override_ratelimit"
    [path_params]="s_user_ratelimit_path_params"
    [body_params]=""
    [minimum_version]="1.32.0rc1"
  )

  declare -Agr s_set_user_ratelimit_api=(
    [method]="POST"
    [path]="/_synapse/admin/v1/users/USER_ID/override_ratelimit"
    [path_params]="s_set_user_ratelimit_path_params"
    [body_params]="s_set_user_ratelimit_body_params"
    [minimum_version]="1.32.0rc1"
  )

  declare -Agr s_delete_user_ratelimit_api=(
    [method]="DELETE"
    [path]="/_synapse/admin/v1/users/USER_ID/override_ratelimit"
    [path_params]="s_delete_user_ratelimit_path_params"
    [body_params]=""
    [minimum_version]="1.32.0rc1"
  )

  declare -Agr s_user_deactivate_api=(
    [method]="POST"
    [path]="/_synapse/admin/v1/deactivate/USER_ID"
    [path_params]="s_user_deactivate_path_params"
    [body_params]="s_user_deactivate_body_params"
  )

  declare -Agr s_user_shadowban_api=(
    [method]="POST"
    [path]="/_synapse/admin/v1/users/USER_ID/shadow_ban"
    [path_params]="s_user_shadowban_path_params"
    [body_params]=""
    [minimum_version]="1.27.0rc1"
  )

  declare -Agr s_user_unshadowban_api=(
    [method]="DELETE"
    [path]="/_synapse/admin/v1/users/USER_ID/shadow_ban"
    [path_params]="s_user_unshadowban_path_params"
    [body_params]=""
    [minimum_version]="1.48.0rc1"
  )

  declare -Agr s_user_redact_api=(
    [method]="POST"
    [path]="/_synapse/admin/v1/user/USER_ID/redact"
    [path_params]="s_user_redact_path_params"
    [body_params]="s_user_redact_body_params"
    [minimum_version]="1.116.0rc1"
  )

  declare -Agr s_user_redact_status_api=(
    [method]="GET"
    [path]="/_synapse/admin/v1/user/redact_status/JOB_ID"
    [path_params]="s_user_redact_status_path_params"
    [body_params]=""
    [minimum_version]="1.116.0rc1"
  )

  declare -Agr s_user_join_room_api=(
    [method]="POST"
    [path]="/_synapse/admin/v1/join/ROOM_ID_OR_ALIAS"
    [path_params]="s_user_join_room_path_params"
    [body_params]="s_user_join_room_body_params"
  )
}
