#!/bin/bash
# Copyright (C) 2021-2024 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

DefineMatrixEndpoints() {
  declare -Agr m_login_api=(
    [method]="POST"
    [path]="/_matrix/client/r0/login"
    [url_params]=""
    [body_params]="m_login_params"
  )

  declare -Agr m_logout_api=(
    [method]="POST"
    [path]="/_matrix/client/r0/logout"
    [url_params]=""
    [body_params]=""
  )

  declare -Agr m_whoami_api=(
	  [method]="GET"
    [path]="/_matrix/client/r0/account/whoami"
    [url_params]=""
    [body_params]=""
  )

  declare -Agr m_resolve_alias_api=(
    [method]="GET"
    [path]="/_matrix/client/r0/directory/room/ALIAS"
    [url_params]="m_resolve_alias_url_params"
    [body_params]=""
  )

  declare -Agr m_create_alias_api=(
    [method]="PUT"
    [path]="/_matrix/client/r0/directory/room/ALIAS"
    [url_params]="m_create_alias_url_params"
    [body_params]="m_create_alias_body_params"
  )

  declare -Agr m_delete_alias_api=(
    [method]="DELETE"
    [path]="/_matrix/client/r0/directory/room/ALIAS"
    [url_params]="m_delete_alias_url_params"
    [body_params]=""
  )

  declare -Agr m_room_visibility_api=(
    [method]="GET"
    [path]="/_matrix/client/v3/directory/list/room/ROOM_ID"
    [url_params]="m_room_visibility_url_params"
    [body_params]="m_room_visiblity_body_params"
  )

  declare -Agr m_room_create_api=(
    [method]="POST"
    [path]="/_matrix/client/v3/createRoom"
    [url_params]=""
    [body_params]="m_room_create_body_params"
  )

  declare -Agr m_server_version_api=(
    [method]="GET"
    [path]="/_matrix/federation/v1/version"
    [url_params]=""
    [body_params]=""
  )
}
