#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixResolveAlias() {
  Log debug "Got args '$*'"

  local -n __MatrixResolveAlias_args="$1"
  case "${__MatrixResolveAlias_args[0]}" in
    create)
      ShiftArray __MatrixResolveAlias_args || return 1
      MatrixCreateAlias __MatrixResolveAlias_args || return 1
      return 0
    ;;
    delete)
      ShiftArray __MatrixResolveAlias_args || return 1
      MatrixDeleteAlias __MatrixResolveAlias_args || return 1
      return 0
    ;;
  esac

  # copy api map to local map
  local -A api
  CopyArray m_resolve_alias_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray m_resolve_alias_url_params url_params

  CheckLoginStatus || return 1

  Log info "Resolving room alias through '${config[homeserver]}'."
  local -A options
  ParseOptions __MatrixResolveAlias_args options
  # ask for alias if not passed
  Log debug "Alias is ${options[alias]}"
  [[ -n "${options[alias]}" ]] || {
    local input_alias
    Read -r -p "$(printf '%s' 'Alias to resolve:')" input_alias
    options[alias]="$input_alias"
  }
  url_params[alias]="${options[alias]}"

  SetPathParameters url_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(servers room_id)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
