#!/bin/bash
# Copyright (C) 2021-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixLogin() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray m_login_api api
  # copy body parameters to local map
  local -A body_params
  CopyArray m_login_body_params body_params

  local -n __MatrixLogin_args="$1"
  local -A options
  ParseOptions __MatrixLogin_args options

  # input
  local mxid="${options[mxid]}"
  [[ -n "$mxid" ]] || {
    Read -r -p "MXID (@user:example.com): " mxid
  }
  local localpart
  local domainpart
  ParseMXID "$mxid" localpart domainpart || return 1
  config[admin_user]="$localpart"
  Log debug "Admin user set to '${config[admin_user]}'."
  body_params[user]="${config[admin_user]}"
  config[homeserver]="$domainpart"

  local homeserver
  GetWellKnown "$domainpart" homeserver || return 1
  ParseServerName "$homeserver" host port || return 1
  config[base_url]="$host"
  [[ "$port" ]] && config[port]="$port"

  [[ -z "${config[admin_token]}" ]] || {
    LogTerm warn "An access token is already present. Logging out..."
    MatrixLogout || return 1
  }

  local password
  [[ -n "${options[password_file]}" ]] && {
    local path="${options[password_file]}"
    password="$(ReadFile "$path")"
  }
  [[ -n "$password" ]] || {
    while Read -s -r -p "password: " password; do
      if [[ -n "$password" ]]; then
        break
      else
        printf '\n'
        LogTerm error "Password required."
      fi
    done
  }
  body_params[password]="$password"

  local save_token="${options[save_token]}"
  [[ -n "$save_token" ]] || {
    local input
    Read -r -p "$(printf '%s' 'Save access token to local config file? (Y/n)')" input
    case "${input^^}" in
      Y|YES|'') save_token="true";;
      N|NO)     save_token="false";;
    esac
  }
  ValidateInput boolean "$save_token" || return 1
  config[save_token]="$save_token"

  GenerateDeviceID
  body_params[device_id]="${config[device_id]}"

  WriteConfiguration
  Log debug "Save ID preference is '${config[save_id]}'"
  Log debug "Device ID is '${config[device_id]}'"

  # construct request body
  local object
  ConstructObject m_login body_params object || return 1

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [data]="$object"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(access_token)
  local -A values
  ProcessResponse response[body] keys values || return 1

  # set token
  config[admin_token]="${values[access_token]}"
  WriteConfiguration
}
