#!/bin/bash
# Copyright (C) 2021-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixWhoAmI() {
  Log debug "Got args '$*'"

  if [[ -z "${config[homeserver]}" ]]; then
    Log error "Failed to determine identity. No homeserver is configured."
    return 1
  fi
  if [[ -z "${config[admin_user]}" ]]; then
    Log error "Failed to determine identity. No user is configured."
    return 1
  fi
  if [[ -z "${config[admin_token]}" ]]; then
    Log error "Failed to determine identity. No access token is present. Do 'login' first."
    return 1
  fi

  local -n __MatrixSetRoomVisibility_args="$1"
  local -A options
  ParseOptions __MatrixSetRoomVisibility_args options

  # copy api map to local map
  local -A api
  CopyArray m_whoami_api api

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(user_id)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
