#!/bin/bash
# Copyright (C) 2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixDiscover() {
  Log debug "Got args '$*'."

  local -n __MatrixDiscover_args="$1"
  local -A options
  ParseOptions __MatrixDiscover_args options
  [[ -n "${options[destination]}" ]] || {
    local input_server_name
    Read -r -p "Server name: " input_server_name
    options[destination]="$input_server_name"
  }

  ValidateInput host "${options[destination]}" || return 1

  local base_url
  GetWellKnown "${options[destination]}" base_url || {
    Log error "Matrix server discovery failed for server '${options[destination]}'"
    return 1
  }

  echo "Base URL: $base_url"
}
