#!/bin/bash
# Copyright (C) 2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixDiscover() {
  Log debug "Got args '$*'."

  local -n __MatrixDiscover_args="$1"
  local -A options
  ParseOptions __MatrixDiscover_args options
  local destination="${options[destination]}"
  [[ -n "$destination" ]] || {
    Read -r -p "Server name: " destination
  }
  ValidateInput host destination || return 1

  local base_url
  GetWellKnown "$destination" base_url || {
    Log error "Matrix server discovery failed for server '$destination'"
    return 1
  }

  echo "Base URL: $base_url"
}
