#!/bin/bash
# Copyright (C) 2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixDiscover() {
  Log debug "Got args '$*'."

  local -n __MatrixDiscover_args="$1"
  local -A options
  ParseOptions __MatrixDiscover_args options
  local destination="${options[destination]}"
  [[ -n "$destination" ]] || {
    Read -r -p "Server name: " destination
  }
  ValidateInput host destination || return 1

  local base_url
  GetWellKnown "$destination" base_url || {
    Log error "Matrix server discovery failed for server '$destination'"
    return 1
  }

  local -a keys=(base_url)
  local -A values=([base_url]="$base_url")
  local output="$base_url"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
