#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixDeleteAlias() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray m_delete_alias_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray m_delete_alias_url_params url_params

  CheckLoginStatus || return 1

  local -n __MatrixDeleteAlias_args="$1"
  local -A options
  ParseOptions __MatrixDeleteAlias_args options
  # ask for alias if not passed
  [[ -n "${options[alias]}" ]] || {
    local input_alias
    Read -r -p "$(printf '%s' 'Alias to delete:')" input_alias
    options[alias]="$input_alias"
  }
  PutArray url_params[alias] "${options[alias]}"

  SetPathParameters url_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [auth]='true'
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }
}
