#!/bin/bash
# Copyright (C) 2022-2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixGetRoomVisibility() {
  Log debug "Got args '$*'"

  local -n __MatrixGetRoomVisibility_args="$1"
  if [[ "${__MatrixGetRoomVisibility_args[0]}" == 'set' ]]; then
    ShiftArray __MatrixGetRoomVisibility_args || return 1
    MatrixSetRoomVisibility __MatrixGetRoomVisibility_args || return 1
    return 0
  fi

  # copy api map to local map
  local -A api
  CopyArray m_room_visibility_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray m_room_visibility_url_params url_params

  CheckLoginStatus || return 1

  local -A options
  ParseOptions __MatrixGetRoomVisibility_args options
  # ask for value if not passed
  local room="${options[room]}"
  [[ -n "$room" ]] || {
    Read -r -p "$(printf '%s' 'Room ID: ')" room
  }
  [[ "${room:0:1}" == '#' ]] && {
    local -a args=(
      alias="$room"
      keys=room_id
      format=plain
    )
    room="$(MatrixResolveAlias args)" || return 1
  }
  url_params[room_id]="$room"

  SetPathParameters url_params api[path]

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  local -a keys=(visibility)
  [[ -z "${options[keys]}" ]] || {
    Explode ',' "${options[keys]}" keys
  }
  local -A values
  ProcessResponse response[body] keys values

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
