#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixCreateAlias() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray m_create_alias_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray m_create_alias_url_params url_params
  # copy body parameters to local map
  local -A body_params
  CopyArray m_create_alias_body_params body_params

  CheckLoginStatus || return 1

  local -n __MatrixCreateAlias_args="$1"
  local -A options
  ParseOptions __MatrixCreateAlias_args options
  # input
  local alias="${options[alias]}"
  [[ -n "$alias" ]] || {
    Read -r -p "$(printf '%s' 'Alias to create:')" alias
  }
  url_params[alias]="${options[alias]}"

  local room="${options[room]:-${options[id]}}"
  [[ -n "$room" ]] || {
    Read -r -p "$(printf '%s' 'Room to link:')" room
  }
  [[ "${room:0:1}" == '#' ]] && {
    local -a args=(
      alias="$room"
      keys=room_id
      format=plain
    )
    room="$(MatrixResolveAlias args)" || return 1
  }
  body_params[room_id]="$room"

  SetPathParameters url_params api[path]

  # construct request body
  local object
  ConstructObject m_create_alias body_params object || return 1

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [data]="$object"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }
}
