#!/bin/bash
# Copyright (C) 2022-2023,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixCreateRoom() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray m_room_create_api api
  # copy body parameters to local map
  local -A body_params
  CopyArray m_room_create_body_params body_params

  CheckLoginStatus || return 1

  Log info "Creating room on '${config[homeserver]}'."

  local -n __MatrixCreateRoom_args="$1"
  local -A options
  ParseOptions __MatrixCreateRoom_args options

  # input
  local room_name="${options[name]}"
  [[ -n "$room_name" ]] || {
    Read -r -p "$(printf '%s' 'Room name:')" room_name
  }
  body_params[name]="$room_name"

  local room_topic="${options[topic]}"
  [[ -n "$room_topic" ]] || {
    Read -r -p "$(printf '%s' 'Room description:')" room_topic
  }
  body_params[topic]="$room_topic"

  local room_preset="${options[preset]}"
  [[ -n "$room_preset" ]] || {
    Read -r -p "$(printf '%s' "Room preset (Type 'help' for more info):")" room_preset
    [[ "$room_preset" == 'help' ]] && {
      local -A presets=(
        [public]='Anyone may join. Members may view all room history. Guests are forbidden.'
        [private]='An invite is required to join. Members may view all room history. Guests are allowed.'
        [trusted]='All members are admins. An invite is required to join. Members may view all room history. Guests are allowed.'
      )
      printf '%s\n' 'Available presets:'
      for preset in "${!presets[@]}"; do
        printf '\t%-7s: %s\n' "$preset" "${presets["$preset"]}"
      done
      MatrixCreateRoom "$1" || return 1
    }
  }
  case "$room_preset" in
      public)
        body_params[preset]='public_chat'
      ;;
      private)
        body_params[preset]='private_chat'
      ;;
      trusted)
        body_params[preset]='trusted_private_chat'
      ;;
      *)
        Log error "Invalid preset '$room_preset', must be one of 'public', 'private', 'trusted'."
        return 1
      ;;
  esac

  local federate="${options[federate]}"
  [[ -n "$federate" ]] || {
    local input
    Read -r -p "$(printf '%s' 'Allow other homeservers to participate? (Y/n): ')" input
    case "$input" in
      [yY]|[Yy][Ee][Ss]|'') federate="true";;
      [Nn]|[Nn][Oo]       ) federate="false";;
    esac
  }
  ValidateInput boolean "$federate" || return 1
  body_params[creation_content.m.federate]="$federate"

  # construct request body
  local object
  ConstructObject m_room_create body_params object || return 1

  # set request parameters
  local -A params=(
    [method]="${api[method]}"
    [path]="${api[path]}"
    [data]="$object"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  local -a keys=(room_id)
  local -A values
  ProcessResponse response[body] keys values || return 1

  local output="${response[body]}"
  FormatOutput "${options[format]}" keys values output || return 1
  printf '%s\n' "$output"
}
