#!/bin/bash
# Copyright (C) 2024-2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixServerVersion() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray m_server_version_api api

  local -n __MatrixServerVersion_args="$1"
  local -A options
  ParseOptions __MatrixServerVersion_args options || return 1
  # ask for server if not passed
  local destination="${options[destination]}"
  [[ -n "$destination" ]] || {
    local input_server
    Read -r -p "Destination:" destination
  }
  ValidateInput host "$destination" || return 1

  Log info "Getting server version for '$destination'"

  local homeserver
  local host
  local port
  {
    GetWellKnown "$destination" homeserver && \
    ParseServerName "$homeserver" host port
  } || {
    Log info "Falling back to default S2S port"
    host="$destination"
    port="8448"
  }

  Log debug "Got host '$host', port '$port', for homeserver '$homeserver'"

  # set request parameters
  local -A params=(
    [host]="$host"
    [port]="$port"
    [method]="${api[method]}"
    [path]="${api[path]}"
    [auth]="false"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }

  # get key values
  local -a keys=(server.name server.version)
  local -A values
  ProcessResponse response[body] keys values || return 1

  # output
  echo "Server name: ${values[server.name]}"
  echo "Server version: ${values[server.version]}"
}
