#!/bin/bash
# Copyright (C) 2022-2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

MatrixSetRoomVisibility() {
  Log debug "Got args '$*'"

  # copy api map to local map
  local -A api
  CopyArray m_room_visibility_api api
  # copy url parameters to local map
  local -A url_params
  CopyArray m_room_visibility_url_params url_params
  # copy body parameters to local map
  local -A body_params
  CopyArray m_room_visibility_body_params body_params

  CheckLoginStatus || return 1

  local -n __MatrixSetRoomVisibility_args="$1"
  local -A options
  ParseOptions __MatrixSetRoomVisibility_args options
  # ask for values if not passed
  [[ -n "${options[id]}" ]] || {
    local input_room_id
    Read -r -p "$(printf '%s' 'Room ID: ')" input_room_id
    options[id]="$input_room_id"
  }
  url_params[room_id]="${options[id]}"

  [[ -n "${options[visibility]}" ]] || {
    local input_visibility
    Read -r -p "$(printf '%s' 'Room visibility (public/private): ')" input_visibility
    options[visibility]="$input_visibility"
  }
  body_params[visibility]="${options[visibility]}"

  # construct request body
  local object
  ConstructObject m_room_visibility body_params object || return 1

  SetPathParameters url_params api[path]

  # set request parameters
  local -A params=(
    [method]="PUT"
    [path]="${api[path]}"
    [data]="$object"
  )
  # make request
  local -A response
  Request params response || return 1
  CheckStatusCode "${response[status]}" || {
    HandleMatrixError response[body]
    return 1
  }
}
