#!/bin/bash
# Copyright (C) 2021-2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

Request() {
  Log debug "Got args '$*'"
  local -n __Request_parameters="$1"
  Assert __Request_parameters HASH
  local method="${__Request_parameters[method]}"
  local path="${__Request_parameters[path]}"
  local data="${__Request_parameters[data]}"
  local host="${__Request_parameters[host]}"
  local auth="${__Request_parameters[auth]}"
  local redirect="${__Request_parameters[redirect]}"
  local -A headers="${__Request_parameters[headers]}"
  local -n __Request_response="$2"
  Assert __Request_response HASH
  local scheme="${config[scheme]}"
  local port="${__Request_parameters[port]}"

  # check for required parameters
  local required_parameters=('method' 'path')
  for parameter in "${required_parameters[@]}"; do
    Log debug "Checking parameter '$parameter', value '${!parameter}'"
    [[ "${!parameter}" ]] || {
      Log fatal "Missing required parameter '$parameter'"
      exit 1
    }
  done

  # if a host wasn't passed then use the configured default
  if [[ -z "$host" ]]; then
    host="${config[base_url]}"
  fi

  # if a port wasn't passed then use the configured default
  if [[ -z "$port" ]]; then
    port="${config[port]}"
  fi

  # construct the URI
  local uri="$scheme://$host:$port$path"
  Log info "Using method '$method' in request to '$uri'"

  # construct the header arg
  local -a header_arg=()
  if [[ -n "${headers[*]}" ]]; then
    for header in "${!headers[@]}"; do
      Log debug "Got header name '$header', value '${headers[$header]}'"
      header_arg+=(--header "${header}: ${headers[$header]}")
    done
    Log debug "Constructed header arg '${header_arg[*]}'"
  fi

  # don't follow redirects unless asked to
  if [[ "$redirect" == 'true' ]]; then
    Log info "Following redirects for this request"
    local redirect_arg="--location"
  else
    Log debug "Not following redirects for this request"
  fi

  # use auth unless asked not to
  if [[ "$auth" == 'false' ]]; then
    Log info "Not sending authorization header for this request"
  else
    Log debug "Sending authorization header for this request"
    local auth_header="Authorization: Bearer ${config[admin_token]}"
  fi

  Log debug "Assembled request '--request $method'"
  Log debug "Assembled request '${data:+--data $data}'"
  Log debug "Assembled request '${redirect_arg:+$redirect_arg}'"
  Log debug "Assembled request '${header_arg[*]}'"
  Log debug "Assembled request '${auth_header:+--header $auth_header}'"
  Log debug "Assembled request '--user-agent ${projectName}/${projectVersion}'"
  Log debug "Assembled request '--write-out $'\t'%{header_json}$'\t'%{response_code}$'\t''"
  Log debug "Assembled request '--silent'"
  Log debug "Assembled request '--show-error'"
  Log debug "Assembled request '--connect-timeout 15'"
  Log debug "Assembled request '--max-time 300'"
  Log debug "Assembled request '$uri'"

  local std_out
  local std_err
  CatchStream std_out std_err curl --request "$method" \
                                   ${data:+--data "$data"} \
                                   ${redirect_arg:+"$redirect_arg"} \
                                   "${header_arg[@]}" \
                                   ${auth_header:+--header "$auth_header"} \
                                   --user-agent "${projectName}/${projectVersion}" \
                                   --write-out $'\t'%{header_json}$'\t'%{response_code}$'\t' \
                                   --silent \
                                   --show-error \
                                   --connect-timeout 15 \
                                   --max-time 300 \
                                   "$uri"

  local return_code="$?"
  if (( "$return_code" > 0 )); then
    Log error "Curl failed with message '$std_err'"
    return 1
  fi

  # remove newlines
  std_out="${std_out//$'\n'/}"

  # separate response body from response code
  local -a response_data
  local part
  while read -r -d $'\t' part; do
    Log debug "Part is '$part'."
    response_data+=("$part")
  done <<<"$std_out"
  local body="${response_data[0]}"
  local header_json="${response_data[1]}"
  local status_code="${response_data[2]}"

  ValidateInput integer "$status_code" || {
    Log fatal "Invalid HTTP status code."
    exit 1
  }
  Log info "Got HTTP status code '$status_code','${http_status_codes[$status_code]}' from '$host'"
  __Request_response[status]="$status_code"
  __Request_response[body]="$body"
  __Request_response[header_json]="$header_json"
}
