#!/bin/bash
# Copyright (C) 2021-2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

CreateFiles() {
  local directory_paths
  local file_paths
  directory_paths=(
    "${config[log_path]}"
    "${config[config_path]}"
  )
  file_paths=(
    "${config[log_path]}/${config[log_file]}"
    "${config[log_path]}/${config[history_file]}"
    "${config[config_path]}/${config[config_file]}"
  )
  local path
  for path in "${directory_paths[@]}"; do
    Log debug "Checking for directory at '$path'..."
    if [[ ! -d "$path" ]]; then
      Log info "Creating directory at '$path'..."
      (umask 077; mkdir --parents "$path") ||
        {
          Log fatal "Failed to create directory at '$path'"
          exit 1
        }
    else
      Log debug "Found '$path'"
    fi
  done
  unset path
  for path in "${file_paths[@]}"; do
    Log debug "Checking for file at '$path'..."
    if [[ ! -f "$path" ]]; then
      Log info "Creating file at '$path'..."
      (umask 066; touch "$path") ||
        {
          Log fatal "Failed to create file at '$path'"
          exit 1
        }
    else
      Log debug "Found '$path'"
      CheckPermissions "$path" "600"
    fi
  done
}
