#!/bin/bash
# Copyright (C) 2021-2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

ReadConfiguration() {
  if [[ -f "${config[config_path]}/${config[config_file]}" ]]; then
    LogTerm config "Found configuration file."
    local line
    while read -r line; do
      LogTerm debug "Line is '$line'"
      if [[ "$line" =~ '=' ]]; then
        LogTerm debug "This looks like config to me..."
        key="${line%%=*}"
        LogTerm debug "Key is '$key'"
        value="${line##*=}"
        LogTerm debug "Value is '$value'"
        config[$key]="$value"
      fi
    done < "${config[config_path]}/${config[config_file]}"
  else
    AXON_FIRST_RUN="true"
    LogTerm warn "First run or missing configuration, using defaults."
  fi
}
