#!/bin/bash
# Copyright (C) 2021-2022,2025 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

WriteConfiguration() {
  Assert config HASH
  local -A persistent_config
  CopyArray config persistent_config
  if [[ "${persistent_config[save_token]}" != true ]]; then
    Log info "Not saving access token due to user preference."
    persistent_config[admin_token]=""
  else
    if [[ -z "${persistent_config[admin_token]}" ]]; then
      [[ "$AXON_FIRST_RUN" ]] || Log debug "User preference set to save access token, but no access token found."
    else
      Log info "Saving access token to config file '${persistent_config[config_path]}/${persistent_config[config_file]}'"
    fi
  fi
  if [[ "${persistent_config[save_id]}" != true ]]; then
    Log info "Not saving device ID due to user preference."
    persistent_config[device_id]=""
  else
    if [[ -z "${persistent_config[device_id]}" ]]; then
      [[ "$AXON_FIRST_RUN" ]] || Log debug "User preference set to save device ID, but no device ID found."
    else
      Log info "Saving device ID to config file '${persistent_config[config_path]}/${persistent_config[config_file]}'"
    fi
  fi
  for key in "${!persistent_config[@]}"; do
    printf '%s=%s\n' "$key" "${persistent_config[$key]}"
  done > "${persistent_config[config_path]}/${persistent_config[config_file]}"
}
