#!/bin/bash
# Copyright (C) 2021-2023,2025,2026 joe <joe@thisisjoes.site>
# SPDX-License-Identifier: GPL-3.0-only

__LINAC_Entrypoint() {
  DefineConfiguration
  ReadEnvironment
  ReadConfiguration
  ReadEnvironment
  CreateFiles
  Log config "Log level set to '${config[log_level]}'"
  Log config "Verbosity set to '${config[verbosity]}'"
  GenerateDeviceID
  WriteConfiguration
  DefineStatusCodes
  DefineObjects
  DefineMatrixBodyParameters
  DefineMatrixPathParameters
  DefineMatrixEndpoints
  DefineSynapseBodyParameters
  DefineSynapsePathParameters
  DefineSynapseQueryParameters
  DefineSynapseEndpoints
  DefineOutputStrings
  CheckDependencies
  if (( "$#" < 1 )); then
    PrintInfo short
    Prompt
  else
    local -a input=("$@")
    HandleCommand input
  fi
}

trap Exit SIGINT SIGQUIT SIGTERM

__LINAC_Entrypoint "$@"
